### ISSUE TITLE
Don't force CAS authentification

### ISSUE THREAD

**Issue by Shnoulle** [univlorraine/limesurvey-cas#2]
Situation:
- I have a CAS account, with admin account on LS
- I have the "global" super admin in LS core system

I want to be allowed to connect to LS admin without my CAS account. And "in general" conect with my CAS account directly.

I think have an option to force or not case here : https://github.com/univlorraine/limesurvey-cas/blob/master/AuthCAS/AuthCAS.php#L158 can be a great idea.

**Comment by goyome** [comment]
Well, that's a tricky question.
When you use CAS authentication, you can't abort once you're redirected to the login page. The only way to be redirected (if my memory is good) is to be CAS authenticated but not in the LDAP population authorized to access the service.

On our install, to be able to connect with the super admin account, I modifiy directly in the database the login of the user with id 1. I set it to my CAS login. It allows me to connect with this special account.

In your case, I assume it's not an option since you probably don't have a CAS account on your client system.
To avoid that, the only way in my opinion would be to define and subscribe "newLoginForm()" function to show a button "CAS authentication" when CAS authentication plugin is selected on the login form and to move all the code concerning CAS redirection from "beforeLogin()" to "newUserSession()". 

I haven't tested that solution because, in my university, we don't want the user to have to select an authentication method.

If you find a way to make it optional in the settings, please send a PR with your modification.

**Comment by Shnoulle** [comment]
Yes, but if your CAS user is not in LS : you can connect.

I don't know phpCAS, sorry. CAS authentification NEED phpCAS::forceAuthentication ? If you don't set it : you don't have CAS auth ?

Sorry : i can't make a PR, i'm not the real user.

**Comment by goyome** [comment]
If your CAS user isn't in LS, you shouldn't be able to connect unless you choose to auto-create user in the settings.

You're right about phpCAS::forceAuthentication. It asks to redirect to CAS if not already authenticated. 
If you want to have multiple choice for authentication, you have to modify the plugin to redirect to CAS after the login form so that you can change the authentication method.

**Comment by Shnoulle** [comment]
Yes, it what i mean : 
- CAS authenticated :
  - default set to true :  take the user from CAS, 401 if not exist (and no autocreate)
  - default set to false :  take the user from CAS, if not exist : Show LS form (like actually)
- CAS unauthenticated 
  - default is set to false/null : Show the "LS core form"
  - default set to true : Go to CAS auth (force) 

I have to create a little CAS authentcation to make a clean pull request ;). Putting this to my big TODO list ...

**Comment by goyome** [comment]
If you just want to check wether or not the user is authenticated, you can use phpCAS::checkAuthentication().
This could help to decide whether or not to show the "LS core form". 
But I honestly don't how to implement it in LS and to keep the possibility to bypass LS authentication form.
I believe I would make this check in beforeLogin() then plug CAS authentication in beforeLogin() or in newUserSession() depending on the new setting "force CAS authentication"...

**Comment by dgeo** [comment]
I saw this problem elsewhere, circumvented by adding '?noCas=true' on url and catching this in auth path of the code…
my 2 cts

**Comment by Shnoulle** [comment]
@goyome or @dgeo : do you have a CAS server for testing ? If yes : send me an email (and an account) : i make a fork of the project and see what we are able to do ?

PS: making it on my freetime ;)

**Comment by goyome** [comment]
@Shnoulle : I think the first tagged version (v0.1) will solve your problem.
Thanks to @dgeo suggestion, I just added a small workaround to force local authentication when CAS plugin is activated. You just have to add noAuthCAS=true to your authentication url (index.php/admin/authentication/sa/login?noAuthCAS=true). This url will redirect you to the classic authentication form.

This is quite specific but as it is primarily meant to access the admin account, I think it will be ok. Works pretty well here.

**Comment by Shnoulle** [comment]
Thank you :)
